### ISSUE TITLE
Thistoo review

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#80]
- [x] create 3 different personas (age/gender/income/children etc)
- [x] run through the app as each (use all tools, complete and generate all forms)
- [x] note pain points, areas of confusion, things not working properly

**Comment by ericatsai77** [comment]
-Information is cut off of form 8A (thistoo divorce application all_simple)
![screen shot 2017-05-08 at 10 17 15 am](https://cloud.githubusercontent.com/assets/28302614/25812260/bb403bdc-33e3-11e7-9461-8263043f35f2.png)

- **Display Error** - Spousal support calculator, person makes $400K per year and spouse makes 0, however the spousal support appears as zero.
![screen shot 2017-05-08 at 10 42 16 am](https://cloud.githubusercontent.com/assets/28302614/25812350/fd4239b8-33e3-11e7-95a8-279113e412dc.png)

- If you are parents of a dependent adult child in university, finances still need to be split in terms of paying for education, however the custody arrangement is not applicable

- In the help centre, the link for rc65 is broken, as well as the Canada Child Tax Benefit

- Health and Dental Benefits - if both parents do not have benefits the option to state that should be available 

- if spouse has an income of zero and is unemployed, the option to enter a value of zero should be allowed.

- For child custody arrangements, the option to add in personalized holidays should be available & the option to make all custody arrangements the same for all children (rather than filling in the form multiple times)

- Option to specify if user has already been separated or not (if they are already separated the app should not lead you to the separation agreement)

**Comment by gabrielladifazio** [comment]
just a few things I noticed
-Went to change the birthday, changed the year of age and clicked out of the screen, does not automatically save→ you had to hit enter on keyboard in order for date of birth not to set to default (current day, 1977), implement a save button or save automatically when click out of date of birth popup? 
-Add labour day, family day* in exceptions, or other/specialized holidays (please specify fill in) 
-Child support tax credit tab (informational blurb says parent with custody usually collects tax credit, could there be an additional point made for what usually happens with joint custody)
-When assets are mentioned, gives the option to redirect to the asset calculator but when I clicked I could not save the page I was currently on (separation agreement) I had exited and lost all progress
-**Got an error 500, when hit generate separation agreement button then all information was deleted, this isn’t happening anymore but was before
Suggestion: 
-Can info (names, birthday, income) be dragged from support calculator into beginning steps of separation agreement instead of having to re-input it?
-for partner’s address in make a “same address checkbox” auto populate field, for if they are still living together, they do not have to type in same address information again
-What if spouse is retired→ income amount, is it zero or the amount from pension?, maybe add an informational content blurbs “info: if your spouse is retired, gross income will be….?” in case people are unsure what to put
